name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1.7.9

      - name: Configure Git
        run: |
          git config --global user.name "Copier Bot"
          git config --global user.email "bot@example.com"

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Generate project from template
        run: uv run copier copy --trust --vcs-ref=HEAD . test-project --defaults

      - name: Template Ruff check
        working-directory: test-project
        run: uv run --only-group lint ruff check --output-format=github

      - name: Template Ruff format
        working-directory: test-project
        run: uv run --only-group lint ruff format --check

      - name: Template Ty check
        working-directory: test-project
        run: uv run --group qa ty check --output-format=github

      - name: Template tests
        working-directory: test-project
        run: uv run --group test pytest

      - name: Template build
        working-directory: test-project
        run: uv build

      - name: Template docs
        working-directory: test-project
        run: make docs
